Run calculator by running cell below.

In [ ]:
#SOURCE CODE OF THE NN
import pandas as pd
import tensorflow as tf
from tensorflow import keras
import numpy as np
from sklearn.preprocessing import OrdinalEncoder
# df = pd.read_csv("numbers_1.txt",delimiter=",", header=None)
# df

In [ ]:
import itertools
import random
print("importing kerass")
from tensorflow.keras.models import model_from_json
import pandas as pd
print("importing numpy")

#ignore this part
a=['zero ','one ', 'two ','three ','four ','five ','six ','seven ','eight ','nine ']
b=['plus ','minus ','multiply ','divide by ' ]
c=a
k=[0,1,2,3,4,5,6,7,8,9]
l=[0,1,2,3]
m=k
sum1=[]
numbers1=[]
for i in range(0,1):
  for r in itertools.product(a,b,c):
    if not (r[1]=='divide by ' and r[2]=='zero '):
      sum1.append(r[0]+r[1]+r[2]+'is equal to')
  for r in itertools.product(k,l,m): 
    value1=r[0]
    value2=r[1]
    if value2==0:
      operation=1
      value3=r[2]
      numbers1.append(value1+value3*(operation))
    elif value2==1:
      operation=-1
      value3=r[2]
      numbers1.append(value1+value3*(operation))
    elif value2==2:
      operation=1
      value3=r[2]
      numbers1.append(value1*value3**(operation))
    elif value2==3:
      operation=-1
      value3=r[2]
      if not value3==0: 
        numbers1.append(value1*value3**(operation))

df_final=pd.DataFrame({'Column1': sum1[:], 'Column2': numbers1[:]})
#loading model
print('Remember to have model.json and model.h5 in the same directiory as the code otherwise it work')
# load json and create model
json_file = open('model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
# load weights into new model
loaded_model.load_weights("model.h5")
print("Loaded model from disk")


X_train=df_final['Column1']
Y_train=df_final['Column2']

Y_train_unique=np.unique(Y_train)
Y_correct=[]
for z in Y_train:
  for ind,y in enumerate(Y_train_unique):
    if y==z:
      #print("hit")
      Y_correct.append(ind)
      break
print('amount of data')
print(len(Y_correct))

Y_train_enc = keras.utils.to_categorical(Y_correct)
print('next value should be 95')
print(len(Y_train_enc[1]))
X_train=X_train.values
# print(X_train)
# print(Y_train)
oe = OrdinalEncoder()
oe.fit(X_train.reshape(-1, 1))
X_train_enc = oe.transform(X_train.reshape(-1, 1))
number_classes = len(np.unique(numbers1))

print("Welcome to stupidest AI ever written, yet (kinda) working.")
print("This AI is calculator and works with numbers up to intiger nine with plus/minus/multiply/divide/by")
print("This model has reached accurary of 66%")
print("Please input the first number")
x=str(input())
if x=="1":
  x='one'
elif x=="2":
  x="two"
elif x=="3":
  x="three"
elif x=="4":
  x="four"
elif x=="5":
  x="five"
elif x=="6":
  x="six"
elif x=="7":
  x="seven"
elif x=="8":
  x="eight"
elif x=="9":
  x="nine"
x=x+" "
print("Please input the operation")
y=str(input())
if y=="+":
  y='plus'
elif y=="-":
  y="minus"
elif y=="*":
  y="multiply"
elif y=="/":
  y="divide by"
y=y+" "
print("Please input the second number")
z=str(input())
if z=="1":
  z='one'
elif z=="2":
  z="two"
elif z=="3":
  z="three"
elif z=="4":
  z="four"
elif z=="5":
  z="five"
elif z=="6":
  z="six"
elif z=="7":
  z="seven"
elif z=="8":
  z="eight"
elif z=="9":
  z="nine"
z=z+' is equal to'
stringinput=x+y+z
print(stringinput)
X_predict=np.array([stringinput])
print(X_predict)
X_predict=oe.transform(X_predict.reshape(-1, 1))
result_argument=loaded_model.predict(X_predict)[0].argmax()
Y_results=np.unique(Y_train)
print(Y_results[result_argument])

importing kerass
importing numpy
Remember to have model.json and model.h5 in the same directiory as the code otherwise it work


FileNotFoundError: ignored

In [ ]:
# #this old version please ignore
# #df
# X_train=df[0]
# Y_train=df[1]
# #Y_train_enc=Y_train.values
# #Y_train_enc=[eval(x) for x in Y_train]

# X_train=X_train.values

# print(X_train)
# print(Y_train)
# oe = OrdinalEncoder()
# oe.fit(X_train.reshape(-1, 1))
# X_train_enc = oe.transform(X_train.reshape(-1, 1))
# number_classes = 10

# Y_train_enc = keras.utils.to_categorical(Y_train, number_classes)
# #X_train_enc=np.asarray(X_train_enc)
# #Y_train_enc=np.asarray(Y_train_enc)
# print(X_train_enc.shape[1])
# print(Y_train_enc)
# #print(X_train_enc.shape[1])

# input_layer = keras.layers.Dense(10,input_dim=X_train_enc.shape[1], name="Input",activation='relu')
# output_layer = keras.layers.Dense(10, activation='softmax', name="Output")
# layer_list=[input_layer, output_layer]
# model = keras.Sequential(layer_list)
# model.summary()
# model.compile(optimizer='sgd',loss='categorical_crossentropy',metrics=['accuracy'])

In [ ]:
# epochs =1500
# history_of_model = model.fit(X_train_enc, Y_train_enc, epochs=epochs, verbose=True)#

In [ ]:
#GENERATES DATA
import itertools
import random
a=['zero ','one ', 'two ','three ','four ','five ','six ','seven ','eight ','nine ']
b=['plus ','minus ','multiply ','divide by ' ]
c=a

k=[0,1,2,3,4,5,6,7,8,9]
l=[+1,-1]
m=k
sum=[]
numbers=[]
# for i in range(0,1):
#   for r in itertools.product(a,b,c): 
#     sum.append(r[0]+r[1]+r[2]+' is equal to')
#   for r in itertools.product(k,l,m): 
#     numbers.append(r[0]+r[1]*r[2])
for i in range(0,1000000):
  d=random.choice(list(enumerate(a)))
  e=random.choice(list(enumerate(b)))
  f=random.choice(list(enumerate(c)))
  string1=str(d[1])
  string2=str(e[1])
  string3=str(f[1])
  if not (string2=='divide by ' and string3=='zero '):
    sum.append(string1+string2+string3+'is equal to')#https://stackoverflow.com/questions/18794390/how-to-get-the-index-of-numpy-random-choice-python
  value1=d[0]
  value2=e[0]
  if value2==0:
    operation=1
    value3=f[0]
    numbers.append(value1+value3*(operation))
  elif value2==1:
    operation=-1
    value3=f[0]
    numbers.append(value1+value3*(operation))
  elif value2==2:
    operation=1
    value3=f[0]
    numbers.append(value1*value3**(operation))
  elif value2==3:
    operation=-1
    value3=f[0]
    if not value3==0: 
      numbers.append(value1*value3**(operation))


print(sum)
print(len(sum))
print(numbers)
print(len(np.unique(numbers))) #look https://www.w3schools.com/python/ref_func_round.asp
print(len(numbers))
df_2=pd.DataFrame({'Column1': sum[:], 'Column2': numbers[:]})
df_2
X_train=df_2['Column1']
Y_train=df_2['Column2']
X_train=X_train.values



IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



95
974869


In [ ]:

# sum=sum1
# numbers=numbers1
print(len(sum))
print(len(numbers))
print(len(np.unique(numbers)))  #number of output
print(len(np.unique(sum)))#number of input
print(len(X_train))

487348
487348
95
390
487348


In [ ]:
from tensorflow.keras import regularizers
#Y_train_enc=Y_train.values
#Y_train_enc=[eval(x) for x in Y_train]


print(X_train)
print(Y_train)
Y_train_unique=np.unique(Y_train)

number_classes = len(np.unique(numbers))#how many cases in 

Y_correct=[]
for z in Y_train:
  for ind,y in enumerate(Y_train_unique):
    if y==z:
      #print("hit")
      Y_correct.append(ind)
      break
print('ilość danych')
print(len(Y_correct))

Y_train_enc = keras.utils.to_categorical(Y_correct)
print(len(Y_train_enc))



oe = OrdinalEncoder()
oe.fit(X_train.reshape(-1, 1))
X_train_enc = oe.transform(X_train.reshape(-1, 1))



#X_train_enc=np.asarray(X_train_enc)
#Y_train_enc=np.asarray(Y_train_enc)
print(X_train_enc.shape[1])
print(Y_train_enc)
print(Y_train_enc)

input_layer = keras.layers.Dense(1560,input_dim=X_train_enc.shape[1], name="Input",activation='relu')
hidden_layer = keras.layers.Dense(390, name="Hidden_layer",activation='relu')#(input_layer)
hidden_layer2 = keras.layers.Dense(360, name="Hidden_layer2",activation='relu',kernel_regularizer=regularizers.L1L2(10e-6))#(hidden_layer)
hidden_layer3 = keras.layers.Dense(120, name="Hidden_layer3",activation='relu')#(hidden_layer2)
output_layer = keras.layers.Dense(95, activation='softmax', name="Output")#(hidden_layer3)
#layer_list=[input_layer, output_layer]
layer_list=[input_layer,hidden_layer,hidden_layer2,hidden_layer3,output_layer]
model2 = keras.Sequential(layer_list)
model2.summary()
model2.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
del Y_correct


['five divide by six is equal to' 'two plus nine is equal to'
 'seven minus eight is equal to' ... 'seven plus three is equal to'
 'six divide by seven is equal to' 'seven multiply two is equal to']
0          0.833333
1         11.000000
2         -1.000000
3          2.000000
4          1.142857
            ...    
487343    32.000000
487344     9.000000
487345    10.000000
487346     0.857143
487347    14.000000
Name: Column2, Length: 487348, dtype: float64
ilość danych
487348
487348
1
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 Input (Dense)               (None, 1560) 

In [ ]:
import sys
import numpy
numpy.set_printoptions(threshold=5)
# numpy.set_printoptions(threshold=sys.maxsize)
# print(Y_train_enc)

In [ ]:
epochs=10
print(len(Y_train_enc[0]))
history_of_model = model2.fit(np.array(X_train_enc), np.array(Y_train_enc), epochs=epochs, verbose=True)#

95
Epoch 1/10
15230/15230 [==============================] - 47s 3ms/step - loss: 2.2425 - accuracy: 0.3235
Epoch 2/10
15230/15230 [==============================] - 48s 3ms/step - loss: 2.2313 - accuracy: 0.3253
Epoch 3/10
15230/15230 [==============================] - 48s 3ms/step - loss: 2.2123 - accuracy: 0.3300
Epoch 4/10
15230/15230 [==============================] - 47s 3ms/step - loss: 2.1944 - accuracy: 0.3340
Epoch 5/10
15230/15230 [==============================] - 49s 3ms/step - loss: 2.1842 - accuracy: 0.3355
Epoch 6/10
15230/15230 [==============================] - 47s 3ms/step - loss: 2.1753 - accuracy: 0.3378
Epoch 7/10
15230/15230 [==============================] - 47s 3ms/step - loss: 2.1594 - accuracy: 0.3398
Epoch 8/10
15230/15230 [==============================] - 48s 3ms/step - loss: 2.1420 - accuracy: 0.3438
Epoch 9/10
15230/15230 [==============================] - 48s 3ms/step - loss: 2.1390 - accuracy: 0.3450
Epoch 10/10
15230/15230 [===========================

In [ ]:
from tensorflow.keras.models import model_from_json
# serialize model to JSON
model_json = model2.to_json()
with open("model_big.json", "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
model2.save_weights("model_big.h5")
print("Saved model to disk")

Saved model to disk


In [ ]:

print(Y_train)
# indexes = np.unique(Y_train, return_index=True)[1]
# Y_results= [Y_train[index] for index in sorted(indexes)]
Y_results=np.unique(Y_train)
print(Y_results)

In [ ]:
loaded_model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 Input (Dense)               (None, 390)               780       
                                                                 
 Hidden_layer (Dense)        (None, 1560)              609960    
                                                                 
 Hidden_layer2 (Dense)       (None, 360)               561960    
                                                                 
 Hidden_layer3 (Dense)       (None, 120)               43320     
                                                                 
 Output (Dense)              (None, 95)                11495     
                                                                 
Total params: 1,227,515
Trainable params: 1,227,515
Non-trainable params: 0
_________________________________________________________________


In [ ]:
print("importing kerass")
from tensorflow.keras.models import model_from_json
print("importing numpy")
import numpy as np
print('Remember to have model.json and model.h5 in the same directiory as the code otherwise it work')
# load json and create model
json_file = open('model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
# load weights into new model
loaded_model.load_weights("model.h5")
print("Loaded model from disk")


X_train=df_2['Column1']
Y_train=df_2['Column2']

Y_train_unique=np.unique(Y_train)



Y_correct=[]
for z in Y_train:
  for ind,y in enumerate(Y_train_unique):
    if y==z:
      #print("hit")
      Y_correct.append(ind)
      break
print('amount of data')
print(len(Y_correct))

Y_train_enc = keras.utils.to_categorical(Y_correct)
print('next value should be 95')
print(len(Y_train_enc[1]))
X_train=X_train.values
# print(X_train)
# print(Y_train)
oe = OrdinalEncoder()
oe.fit(X_train.reshape(-1, 1))
X_train_enc = oe.transform(X_train.reshape(-1, 1))
number_classes = len(np.unique(numbers))#how many cases in 



importing kerass
importing numpy
Remember to have model.json and model.h5 in the same directiory as the code otherwise it work
Loaded model from disk
amount of data
974869
next value should be 95
95


In [ ]:
epochs=5
loaded_model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
history_of_model = loaded_model.fit(X_train_enc, Y_train_enc, epochs=epochs, verbose=True)#



Epoch 1/5
30465/30465 [==============================] - 94s 3ms/step - loss: 1.7467 - accuracy: 0.4531
Epoch 2/5
30465/30465 [==============================] - 95s 3ms/step - loss: 1.7400 - accuracy: 0.4562
Epoch 3/5
30465/30465 [==============================] - 94s 3ms/step - loss: 1.7424 - accuracy: 0.4564
Epoch 4/5
30465/30465 [==============================] - 94s 3ms/step - loss: 1.7338 - accuracy: 0.4583
Epoch 5/5
30465/30465 [==============================] - 96s 3ms/step - loss: 1.7222 - accuracy: 0.4614


In [ ]:
from tensorflow.keras.models import model_from_json
# serialize model to JSON
model_json = loaded_model.to_json()

with open("model.json", "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
loaded_model.save_weights("model.h5")
print("Saved model to disk")

Saved model to disk


In [ ]:
print("Welcome to stupidest AI ever written, yet (kinda) working.")
print("This AI is calculator and works with numbers up to intiger nine with plus/minus/multiply/divide/by")
print("This model has reached accurary of 66%")
print("Please input the first number")
x=str(input())
if x=="1":
  x='one'
elif x=="2":
  x="two"
elif x=="3":
  x="three"
elif x=="4":
  x="four"
elif x=="5":
  x="five"
elif x=="6":
  x="six"
elif x=="7":
  x="seven"
elif x=="8":
  x="eight"
elif x=="9":
  x="nine"
x=x+" "
print("Please input the operation")
y=str(input())
if y=="+":
  y='plus'
elif y=="-":
  y="minus"
elif y=="*":
  y="multiply"
elif y=="/":
  y="divide by"
y=y+" "
print("Please input the second number")
z=str(input())
if z=="1":
  z='one'
elif z=="2":
  z="two"
elif z=="3":
  z="three"
elif z=="4":
  z="four"
elif z=="5":
  z="five"
elif z=="6":
  z="six"
elif z=="7":
  z="seven"
elif z=="8":
  z="eight"
elif z=="9":
  z="nine"
z=z+' is equal to'
stringinput=x+y+z
print(stringinput)
X_predict=np.array([stringinput])
print(X_predict)
X_predict=oe.transform(X_predict.reshape(-1, 1))
result=loaded_model.predict(X_predict)[0].argmax()
print(result)

In [ ]:

X_predict=np.array(['four multiply three is equal to'])
X_predict=oe.transform(X_predict.reshape(-1, 1))
print(X_predict)
loaded_model.predict(X_predict)
#print(loaded_model.predict(X_predict)[0])
print(loaded_model.predict(X_predict)[0].argmax())
argument=loaded_model.predict(X_predict)[0].argmax()
print(argument)
print(Y_results[argument])



In [ ]:
import itertools
import random
a=['zero ','one ', 'two ','three ','four ','five ','six ','seven ','eight ','nine ']
b=['plus ','minus ','multiply ','divide by ' ]
c=a
k=[0,1,2,3,4,5,6,7,8,9]
l=[0,1,2,3]
m=k
sum1=[]
numbers1=[]
for i in range(0,1):
  for r in itertools.product(a,b,c):
    if not (r[1]=='divide by ' and r[2]=='zero '):
      sum1.append(r[0]+r[1]+r[2]+'is equal to')
  for r in itertools.product(k,l,m): 
    value1=r[0]
    value2=r[1]
    if value2==0:
      operation=1
      value3=r[2]
      numbers1.append(value1+value3*(operation))
    elif value2==1:
      operation=-1
      value3=r[2]
      numbers1.append(value1+value3*(operation))
    elif value2==2:
      operation=1
      value3=r[2]
      numbers1.append(value1*value3**(operation))
    elif value2==3:
      operation=-1
      value3=r[2]
      if not value3==0: 
        numbers1.append(value1*value3**(operation))

    # if r[1]==11:
    #   numbers1.append(r[0]+r[1]*r[2])
    # if r[1]==1 and not r[2]==0:
    #     numbers1.append(r[0]*r[1]**r[2])


print(sum1)
print(numbers1)
print(len(np.unique(sum1)))
print(len(np.unique(numbers1)))

df_3=pd.DataFrame({'Column1': sum1[:], 'Column2': numbers1[:]})
df_3


In [ ]:
i=0
Y_results=np.unique(Y_train)
for r in sum1:
  result_arg=0
  result_Y=0
  X_predict=np.array([r])
  X_predict=oe.transform(X_predict.reshape(-1, 1))
  #print(X_predict)
  #loaded_model.predict(X_predict)
  argument=loaded_model.predict(X_predict)[0].argmax()
  print(r)
  #print(argument)
  print(Y_results[argument])
  #print(loaded_model.predict(X_predict)[0])
  # print(loaded_model.predict(X_predict)[0].argmax())
  # if argument==numbers1[i]:
  #   result_arg+=1
  if Y_results[argument]==numbers1[i]:
    result_Y+=1
  i+=1
  print(i)
print(result_arg)
print(result_Y)
